# docker compose with extends docker compose files # so weir ! i can't run on build-basic-webapp-using-angular-and-node but can run on build-basic-webapp-using-angular-and-node/backend
version: '3'

services:
  backend:
    # can extends service that you need
    extends:
      # specify file
      file: backend/docker-compose-backend.yml
      # specify service that you want to map, Remember you can use the same service name
      service: backend

  database:
    extends:
      file: backend/docker-compose-database.yml
      service: database

  frontend:
    extends:
      file: docker-compose-angular.yml
      service: frontend

# have to set it again because it can't see
volumes: # for storing value on container (can call service in backend part)
  information-database: # define volume name
    driver: local # use only current pc
