version: '3'
services:
  backend:
    container_name: api
    build:
      context: . # relative to docker-compose command running directory (.) means this folder (below)
      dockerfile: dockers/nodejs/Dockerfile # specify path to Dockerfile it starts on current folder application
    image: node_js # set repository name or image name
    ports: # it's cool command, So you do not need to specify -p <port access runtime>:<port on container> when build
      - '3200:3232'
    links: # to link containers over a network. When we link containers, Docker creates environment variables and adds containers to the known hosts list
      - database
    volumes:
      - information-database:/var/lib/mysql

