version: '3'
services:
  database:
    container_name: mysql # define container name
    restart: always # I ask docker-compose.yml to always restart this container if it fails.
    image: mysql
    environment: # set up database config
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    ports:
      - '3307:${PORT}'
    volumes:
      # second way use with your volume for storing data (use volume name instead folder name)
      - information-database:/var/lib/mysql
    env_file: # Use the env_file attribute for config .env files (this case name should be .env)
      - ./.env # run tru B:\practice-docker\build-basic-webapp-using-angular-and-node\docker-compose.yml it'll start on B:\practice-docker\build-basic-webapp-using-angular-and-node\

volumes: # for storing value on container (can call service in backend part)
  # - information-database:/var/lib/mysql
  # same result as information-database:
  information-database: # define volume name
    driver: local # use only current pc


